---
- name: Hardening the OS by enabling UFW, install Fail2ban and SSH lockdown.
  hosts: homelab
  become: yes 
  
  tasks:
  - name: Allow SSH trafic UFW.
    community.general.ufw:
        rule: allow 
        name: OpenSSH
  
  - name: Enable UFW and set default policy.
    community.general.ufw:
        state: enabled
        default: deny
        direction: incoming

  - name: Install the Fail2ban package.
    ansible.builtin.apt:
        name: fail2ban
        update_cache: yes

  - name: Run daemon on boot.
    ansible.builtin.systemd_service:
        name: fail2ban
        enabled: true
        state: started

  - name: Disable Root Login 
    ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: PermitRootLogin no

  - name: Disable Password Authentication.
    ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: PasswordAuthentication no

  - name: Neutralize cloud-init password overrides.
    ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf 
        state: absent

  - name: Restart SSH Service to apply changes.
    ansible.builtin.systemd_service:
        name: ssh
        state: restarted
