--- 
name: Ansible Lint check

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml

      - name: Run ansible-lint
        run: ansible-lint ./ansible
