--- 
name: Ansible Lint check

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  pull_request:
    branches:
      - main
    paths:
      - 'ansible/**'

jobs:
  ansible-lint:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 
        
      - name: Run ansible-lint
        run: ansible-lint ./ansible 
