name: Deploy Nextcloud

on:
  push:
    branches:
      - main
    paths:
      - 'nextcloud/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fetch Latest Code & Deploy
        run: |
          cd /home/cargo/docker/nextcloud 

          git fetch --all
          git reset --hard origin/main
          
          docker compose up -d --remove-orphans
