name: Deploy NPM 

on:
  push:
    branches:
      - main
    paths:
      - 'npm/**'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Fetch Latest Code & Deploy
        run: |
          cd /home/cargo/docker/npm 

          git fetch --all 
          git reset --hard origin/main 

          docker compose up -d --remove-orphans
